config/routes.rb
Rails.application.routes.draw do
  resources :feetbacks
  resources :requests
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'confirm' => :confirm
    post 'restore_pass' => :restore_pass
    get 'restore_pass' => :restore_pass
    delete 'logout' => :destroy
  end

  controller :users do
    get 'registration' => :new
    post 'registration' => :create
  end

  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  resources :line_items
  resources :carts
  get 'store/index'

  resources :products
  root to: 'store#index', as: 'store'

  

end

app/models/feetback.rb
class Feetback < ActiveRecord::Base
  belongs_to :user
end

app/controllers/feetbacks_controller.rb
class FeetbacksController < ApplicationController
  before_action :set_feetback, only: [:show, :edit, :update, :destroy]

  # GET /feetbacks
  # GET /feetbacks.json
  def index
    @feetbacks = Feetback.all
  end

  # GET /feetbacks/1
  # GET /feetbacks/1.json
  def show
  end

  # GET /feetbacks/new
  def new
    @feetback = Feetback.new
  end

  # GET /feetbacks/1/edit
  def edit
  end

  # POST /feetbacks
  # POST /feetbacks.json
  def create
    @feetback = Feetback.new(feetback_params)

    respond_to do |format|
      if @feetback.save
        format.html { redirect_to @feetback, notice: 'Feetback was successfully created.' }
        format.json { render :show, status: :created, location: @feetback }
      else
        format.html { render :new }
        format.json { render json: @feetback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feetbacks/1
  # PATCH/PUT /feetbacks/1.json
  def update
    respond_to do |format|
      if @feetback.update(feetback_params)
        format.html { redirect_to @feetback, notice: 'Feetback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feetback }
      else
        format.html { render :edit }
        format.json { render json: @feetback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feetbacks/1
  # DELETE /feetbacks/1.json
  def destroy
    @feetback.destroy
    respond_to do |format|
      format.html { redirect_to feetbacks_url, notice: 'Feetback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feetback
      @feetback = Feetback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feetback_params
      params.require(:feetback).permit(:text, :user_id, :mark)
    end
end

app/views/feetbacks/_form.html.erb
<%= form_for(@feetback) do |f| %>
  <% if @feetback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feetback.errors.count, "error") %> prohibited this feetback from being saved:</h2>

      <ul>
      <% @feetback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :mark %><br>
    <%= f.number_field :mark %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feetbacks/edit.html.erb
<h1>Editing Feetback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feetback %> |
<%= link_to 'Back', feetbacks_path %>

app/views/feetbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Feetbacks</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>User</th>
      <th>Mark</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feetbacks.each do |feetback| %>
      <tr>
        <td><%= feetback.text %></td>
        <td><%= feetback.user %></td>
        <td><%= feetback.mark %></td>
        <td><%= link_to 'Show', feetback %></td>
        <td><%= link_to 'Edit', edit_feetback_path(feetback) %></td>
        <td><%= link_to 'Destroy', feetback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feetback', new_feetback_path %>

app/views/feetbacks/new.html.erb
<h1>New Feetback</h1>

<%= render 'form' %>

<%= link_to 'Back', feetbacks_path %>

app/views/feetbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @feetback.text %>
</p>

<p>
  <strong>User:</strong>
  <%= @feetback.user %>
</p>

<p>
  <strong>Mark:</strong>
  <%= @feetback.mark %>
</p>

<%= link_to 'Edit', edit_feetback_path(@feetback) %> |
<%= link_to 'Back', feetbacks_path %>