config/routes.rb
Rails.application.routes.draw do
  resources :feetbacks
  resources :requests
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'confirm' => :confirm
    post 'restore_pass' => :restore_pass
    get 'restore_pass' => :restore_pass
    delete 'logout' => :destroy
  end

  controller :users do
    get 'registration' => :new
    post 'registration' => :create
  end

  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  resources :line_items
  resources :carts
  get 'store/index'

  resources :products
  root to: 'store#index', as: 'store'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StuffExchange</title>
  <!-- BOOTSTRAP -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
	

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</head>
<body class='<%= controller.controller_name %>' style="background-color: #f7f7f7">

	<div id="main_pannel">
		<ul>
			<li><%= link_to 'Home',store_path %></li>
			<%if session[:user_id]%>				

			<span class="hline"></span>
			<li><%= link_to 'My Products',products_path %></li>

			<span class="hline"></span>
			<li><%= link_to 'My Profile',edit_user_path(session[:user_id]) %></li>

			<span class="hline"></span>
			<li><%= link_to 'Requests',requests_path %></li>
			
			<span class="hline"></span>
			<li><%= link_to "My Cart", @cart%><span id="cart_quantity"><%= render @cart%></span></li>
			
			<span class="hline"></span>
			<li><%= link_to 'Logout', logout_path, method: :delete %></li>
			<%else%>
			<span class="hline"></span>
			<li><%= link_to 'Login', login_path, method: :new %></li>
			<span class="hline"></span>
			<li><%= link_to 'Registration', registration_path %></li>
			<%end%>
		</ul>
	</div> 
	<div id="banner_pannel">	
		<div id="banner"><%=@page_title || "Stuff Exchange" %></div>
		<%if controller.controller_name=="store"%>
			<div id="search_field">
				<%= form_tag(store_path, method: "get", class: "search_form form-inline") do %>
				 	<%= text_field_tag(:search_title, "", size: 30, placeholder: 'Search for...', class: "form-control") %>	
				 	<%= select_tag "cathegory", options_from_collection_for_select(@cathegories, "id", "name"),include_blank: "Cathegory", class: "form-control" %>		
					<%= select_tag "country", options_from_collection_for_select(@countries, "id", "name"), include_blank: "Country", class: "form-control" %>			
					<%= submit_tag "Search", :name => nil , class: "btn btn-primary"%>
				<% end %>
			</div>
		<%else%>
			 <span id="title"><%=flash[:title]%></span>
		<%end%>	
	</div>
	<div class="wline"></div>	
	<div id="main">
		<%= yield %>
	</div>		
	
</body>
</html>